---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - python3-debian
    state: present

- name: Add Kubernetes repository.
  deb822_repository:
    name: kubernetes
    types: deb
    uris: "{{ kubernetes_apt_repository }}"
    suites: /
    signed_by: "{{ kubernetes_apt_repository }}/Release.key"

- name: Add Kubernetes apt preferences file to pin a version.
  template:
    src: apt-preferences-kubernetes.j2
    dest: /etc/apt/preferences.d/kubernetes
    mode: 0644
